[features]
seeds = false
skip-lint = false
[programs.localnet]
todo = "H2GTK5fQwrZPkT9QiZvujUad9UB1k69P7CCbLxiQHeGj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/0xcen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

